// demo-vue/src/views/article/module/detail/index.vue
<template>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 blog-main">
                <div class="blog-post">
                    <hr>
                    <div v-html="content"></div>
                </div>
            </div>
        </div>
        <hr>
    </div>
</template>
<script>
import Service from './service';
export default {
    data() {
            return {
                content: ""
            }
        },
        props: {
            id: {
                type: Number,
                default: 0
            }
        },
        watch: {
            id: function(val, oldVal) {
                this.jumbotron(val);
            }
        },
        methods: {
            jumbotron: function(id) {
                let _vm = this;
                Service.renderData(id).then((data) => {
                    _vm.content = data.content;
                });
            }
        }
}
</script>

// demo-react/src/views/article/module/detail/index.js
import Service from './service';

export default React.createClass({
    getInitialState() {
        return {
            content: ""
        };
    },
    componentDidMount() {
        Service.renderData(this.props.id).then((data) => {
            this.setState({
                content: data.content
            });
        });
    },
    render() {
        return (
            <div className="container">
        <div className="row">
            <div className="col-sm-12 blog-main">
                <div className="blog-post">
                    <hr />
                    <div dangerouslySetInnerHTML={{
                __html: this.state.content
            }}></div>
                </div>
            </div>
        </div>
        <hr />
    </div>
        );

    }
});
