// demo-vue/src/views/article/module/detail/jumbotron.vue
<template>
    <div class="jumbotron">
        <div class="container">
            <h1>hello,{{jumbotronData.title}}!</h1>
            <p>{{jumbotronData.desc}}</p>
            <p>
                <a class="btn btn-primary btn-lg" :href="jumbotronData.viewMore.href" role="button">{{jumbotronData.viewMore.text}}
                </a>
            </p>
        </div>
    </div>
</template>
<script>
import Service from './service';
import urlParam from 'public/utils/url-param';
export default {
    data() {
            return {
                jumbotronData: {
                    title: "",
                    desc: "",
                    viewMore: {
                        name: ``,
                        href: ""
                    }
                }
            }
        },
        props: {
            id: {
                type: String,
                default: 0
            }
        },
        watch: {
            id: function(val, oldVal) {
                this.jumbotron(val);
            }
        },
        methods: {
            jumbotron: function(id) {
                let _vm = this;
                Service.renderData(id).then((data) => {
                    _vm.jumbotronData = Object.assign({}, data);
                });
            }
        }
}
</script>

// demo-react/src/views/article/module/detail/jumbotron.js
import Service from './service';

export default React.createClass({
    getInitialState() {
        return {
            jumbotronData: {
                title: "",
                desc: "",
                viewMore: {
                    name: ``,
                    href: ""
                }
            }
        };
    },
    componentDidMount() {
        Service.renderData(this.props.id).then((data) => {
            this.setState({
                jumbotronData: Object.assign({}, data)
            });
        });
    },
    render() {
        return (
            <div className="jumbotron">
        <div className="container">
            <h1>hello,{this.state.jumbotronData.title}!</h1>
            <p>{this.state.jumbotronData.desc}</p>
            <p>
                <a className="btn btn-primary btn-lg" href={this.state.jumbotronData.viewMore.href} role="button">{this.state.jumbotronData.viewMore.text}
                </a>
            </p>
        </div>
    </div>
        );

    }
});
