// demo-vue/src/views/list/module/jumbotron/index.vue
<template>
    <div class="jumbotron">
        <div class="container">
            <h1 v-text="jumbotronData.title"></h1>
            <p v-text="jumbotronData.content"></p>
            <p>
                <a class="btn btn-primary btn-lg" :href="jumbotronData.button.href" role="button" v-html="jumbotronData.button.name"></a>
            </p>
        </div>
    </div>
</template>
<script>
import Service from './service'

export default {
    data() {
            return {
                jumbotronData: {
                    title: "",
                    content: "",
                    button: {
                        name: ``,
                        href: ""
                    }
                }
            }
        },
        methods: {
            jumbotron: function() {
                let _vm = this
                Service.renderData().then((data) => {
                    _vm.jumbotron = Object.assign(_vm.jumbotronData, data)
                })
            }
        },
        created() {
            this.jumbotron()
        }
}
</script>

// demo-react/src/views/list/module/jumbotron/index.js
import Service from './service'

export default React.createClass({
    getInitialState() {
        return {
            jumbotronData: {
                title: "",
                content: "",
                button: {
                    name: ``,
                    href: ""
                }
            }
        }
    },
    componentDidMount() {

        Service.renderData().then((data) => {
            this.setState({
                jumbotronData: Object.assign({}, data)
            })
        })
    },
    render() {
        return (
            <div className="jumbotron">
        <div className="container">
            <h1>{this.state.jumbotronData.title}</h1>
            <p>{this.state.jumbotronData.content}</p>
            <p>
                <a className="btn btn-primary btn-lg" href={this.state.jumbotronData.button.href} role="button" dangerouslySetInnerHTML={{
                __html: this.state.jumbotronData.button.name
            }}></a>
            </p>
        </div>
    </div>
        )

    }
})
