// demo-vue/src/views/index/index.vue
<template>
    <fez-page>
        <fez-jumbotron></fez-jumbotron>
        <fez-fezdesc></fez-fezdesc>
    </fez-page>
</template>
<script>
import fezPage from 'public/module/common/page.vue';
import fezJumbotron from './module/jumbotron/index.vue';
import fezFezdesc from './module/fezdesc/index.vue';

export default {
    components: {
        fezPage,
        fezJumbotron,
        fezFezdesc
    }
}
</script>

// demo-react/src/views/index/index.js
import React from 'react';
import ReactDOM from 'react-dom';

import Header from 'public/module/common/header';
import Jumbotron from './module/jumbotron/index';
import Fezdesc from './module/fezdesc/index';
import Footer from 'public/module/common/footer';


let Page = React.createClass({
	render() {
		return (
			<div>
        <Header />
        <Jumbotron />
        <Fezdesc />
        <Footer />
        </div>
		);
	}
});

ReactDOM.render(
	<Page />,
	document.getElementById('app')
);
