// demo-vue/src/views/index/module/fezdesc/index.vue
<template>
    <div class="container fezdesc">
        <div class="row">
            <div class="col-md-12">
                <h3>{{fezdesc}}</h3>
                <div class="fez-big-logo"></div>
            </div>
        </div>
        <hr>
    </div>
</template>
<script>
import Service from './service';
export default {
    data() {
            return {
                fezdesc: ""
            }
        },
        methods: {
            fezdescInit: function() {
                let _vm = this;
                Service.renderData().then((data) => {
                    _vm.fezdesc = data;
                });
            }
        },
        created() {
            this.fezdescInit();
        }
}
</script>

// demo-react/src/views/index/module/fezdesc/index.js
import Service from './service';

export default React.createClass({
    getInitialState() {
        return {
            fezdesc: ""
        };
    },
    componentDidMount() {

        Service.renderData().then((data) => {
            this.setState({
                fezdesc: data
            });
        });
    },
    render() {
        return (
            <div className="container fezdesc">
        <div className="row">
            <div className="col-md-12">
                <h3>{this.state.fezdesc}</h3>
                <div className="fez-big-logo"></div>
            </div>
        </div>
        <hr />
    </div>
        );

    }
});
