// demo-react/src/views/list/index.js
import React from 'react';
import ReactDOM from 'react-dom';

import Header from 'public/module/common/header';
import Jumbotron from './module/jumbotron/index';
import Listing from './module/listing/index';
import Footer from 'public/module/common/footer';


const Page = React.createClass({
  render() {
    return (
      <div>
        <Header />
        <Jumbotron />
        <Listing />
        <Footer />
      </div>
    );
  }
});

ReactDOM.render(
  <Page />,
  document.getElementById('app')
);

// demo-vue/src/views/list/index.vue
<template>
    <fez-page>
        <fez-jumbotron></fez-jumbotron>
        <fez-listing></fez-listing>
    </fez-page>
</template>
<script>
import fezPage from 'public/module/common/page.vue'
import fezJumbotron from './module/jumbotron/index.vue'
import fezListing from './module/listing/index.vue'

export default {
    components: {
        fezPage,
        fezJumbotron,
        fezListing
    }
}
</script>
