// demo-react/src/views/public/module/common/footer.js
import Service from './common';

export default React.createClass({
    getInitialState() {
        return {
            footerText: ""
        };
    },
    componentDidMount() {
        Service.footerText().then((data) => {
            this.setState({
                footerText: data
            });
        });
    },
    render() {

        return (<footer className="container">
        <span className="pull-left">{this.state.footerText}</span>
        <span className="pull-right">
        <i className="icon icon-weixin"></i>
        <i className="icon icon-weibo"></i>
    </span>
    </footer>);

    }
});

// demo-vue/src/views/public/module/common/footer.vue
<template>
    <footer class="container">
        <span class="pull-left">{{text}}</span>
        <span class="pull-right">
		<i class="icon icon-weixin"></i>
		<i class="icon icon-weibo"></i>
	</span>
    </footer>
</template>
<script>
import Service from './common'
export default {
    data() {
            return {
            	text:""
            }
        },
        methods: {
            footer: function() {
                Service.footerText().then((data) => {
                	this.text = data
                })
            }
        },
        created() {
        	this.footer()
        }
}
</script>
