// demo-react/src/views/article/index.js
import React from 'react'
import ReactDOM from 'react-dom'

import Header from 'public/module/common/header'
import Jumbotron from './module/detail/jumbotron'
import Detail from './module/detail/index'
import Footer from 'public/module/common/footer'

import urlParam from 'public/utils/url-param'

urlParam('id').then((data) => {
	let Page = React.createClass({
		render() {
			return (
				<div>
        <Header />
        <Jumbotron id={data}/>
        <Detail id={data}/>
        <Footer />
        </div>
			)
		}
	})

	ReactDOM.render(
		<Page />,
		document.getElementById('app')
	)
})

// demo-vue/src/views/article/index.vue
<template>
    <fez-page>
        <fez-jumbotron :id="id"></fez-jumbotron>
        <fez-detail :id="id"></fez-detail>
    </fez-page>
</template>
<script>
import fezPage from 'public/module/common/page.vue';
import fezJumbotron from './module/detail/jumbotron.vue';
import fezDetail from './module/detail/index.vue';

import urlParam from 'public/utils/url-param';

export default {
    data() {
            return {
                id: ""
            }
        },
        components: {
            fezPage,
            fezJumbotron,
            fezDetail
        },
        created() {
            let _vm = this;
            urlParam('id').then((data) => {
                _vm.id = data;
            });
        }
}
</script>
